<?php

########################################################################
# Extension Manager/Repository config file for ext: "jh_theanswer"
#
# Auto generated by Extension Builder 2014-04-09
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'THE ANSWER',
	'description' => 'Gives us the Answer to The Ultimate Question of Life, the Universe, and Everything.',
	'category' => 'example',
	'author' => 'Juerg Hunziker',
	'author_email' => 'juerg.hunziker@gmail.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'test',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '42.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>